### PR TITLE
Incorrect path in tsd.json

### PR DESCRIPTION
**Pull request by lukephills**
typings should be added to config/typings file

### CODE REVIEW

**Comment by lukephills** [comment]
Also I'm not sure whether typings.json is needed if we're already using tsd

**Comment by Kflash** [comment]
@lukephills Hey. From next version of TypeScript - v. 2.0 - TSD and typings are both deprecated. NPM are used as an replacement.

If you want to look into something cool, you can [click here](https://github.com/Kflash/sikky).

Trixly moved and got a huge refactor. Still early progress. Struggling with Webpack 2.0 integration now.

**Comment by lukephills** [comment]
@Kflash Thanks! Sikky looks great. I'm so glad I found some up-to-date typescript/webpack workflows. Do you think you'll add a simple `npm start` command that just starts up a webpack-dev-server and updates modules on changes?

**Comment by Kflash** [comment]
@lukephills Nice to know you liked it :) I'm trying to build a ultimate workflow that will always be up-to-date. A huge task for a single person :-)

 As it is now I have a lot of stuff on my todo list for Sikky, but yes I plan to add a `npm start`. 

Or if you have time and will, why not send a PR? It would be to great help :-)

**Pull request merged**
